version: '3.4'

services:
  socialnetwork.portal:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8000:80"
      - "8001:443"

  socialnetwork.profile.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8002:80"

  socialnetwork.identityserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "8843:443"
      - "8003:80"
