version: '3.4'

services:
  socialnetwork.portal:
    image: mental001/socialnetwork.portal
    build:
      context: ../../
      dockerfile: src/WebApps/SocialNetwork.Portal/Dockerfile

  socialnetwork.profile.api:
    image: mental001/socialnetwork.profile.api
    build:
      context: ../../
      dockerfile: src/Services/Profile/SocialNetwork.Profile.API/Dockerfile

  socialnetwork.identityserver:
    image: mental001/socialnetwork.identityserver
    build:
      context: ../../
      dockerfile: src/WebApps/SocialNetwork.IdentityServer/Dockerfile
