apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-deployment
  labels:
    app: portal
spec:
  replicas: 5
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
    spec:
      containers:
        - name: portal
          image: mental001/socialnetwork.portal:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          resources:
            limits:
              memory: "256Mi"
              cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: portal-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: SocialNetwork
    service.beta.kubernetes.io/azure-dns-label-name: socialnetwork
spec:
  type: LoadBalancer
  loadBalancerIP: 20.107.187.197
  selector:
    app: portal
  ports:
    - protocol: TCP
      port: 80


