apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-deployment
  labels:
    app: portal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
    spec:
      containers:
        - name: portal
          image: mental001/socialnetwork.portal
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: "https://+:443;http://+:80"
            - name: ASPNETCORE_Kestrel__Certificates__Default__Password
              value: "123"
            - name: ASPNETCORE_Kestrel__Certificates__Default__Path
              value: "/https/aspnetapp.pfx"
          resources:
            limits:
              memory: "256Mi"
              cpu: "300m"
          volumeMounts:
            - mountPath: /https
              name: portal-ssl-certificate
      volumes:
        - name: portal-ssl-certificate
          secret:
            secretName: portal-ssl-certificate
            defaultMode: 0444
---
apiVersion: v1
kind: Service
metadata:
  name: portal-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: SocialNetwork
    service.beta.kubernetes.io/azure-dns-label-name: socialnetwork
spec:
  type: LoadBalancer
  # loadBalancerIP: 20.166.88.23
  selector:
    app: portal
  ports:
    - name: http
      protocol: TCP
      port: 80
    - name: https
      protocol: TCP
      port: 443
