apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-deployment
  labels:
    app: portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
    spec:
      containers:
        - name: portal
          image: mental001/socialnetwork.portal:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: "https://+:443;http://+:80"
            - name: ASPNETCORE_Kestrel__Certificates__Default__Password
              value: ""
            - name: ASPNETCORE_Kestrel__Certificates__Default__Path
              value: "/https/localhost.pfx"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /cache
              name: cache-volume
            - mountPath: /https
              name: ssl-certificate
      volumes:
        - name: cache-volume
          emptyDir: {}
        - name: ssl-certificate
          secret:
            secretName: ssl-certificate
            defaultMode: 0444
---
apiVersion: v1
kind: Service
metadata:
  name: portal-service
spec:
  type: NodePort
  selector:
    app: portal
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 80
      nodePort: 30000
    - name: https
      protocol: TCP
      port: 8001
      targetPort: 443
      nodePort: 31000
