name: ci

on: [push]
#on:
#  push:
#    branches:
#      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # Build image and deploy to Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./src/WebApps/SocialNetwork.Portal/Dockerfile
          push: true
          tags: mental001/socialnetwork.portal:latest

      - uses: azure/setup-kubectl@v2.0

      # Set the target AKS cluster.
      - uses: Azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: SocialNetworkCluster
          resource-group: SocialNetwork

      - uses: Azure/k8s-deploy@v3.1
        with:
          action: deploy
          manifests: |
              ./deployment/aks/portal.yaml
          images: |
              mental001/socialnetwork.portal:latest
