name: CI-CD

on:
  push:
    branches:
      - 'main'

jobs:

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal

  docker:
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - name: Checkout the git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Build Portal image
      - name: Build and push Portal
        uses: docker/build-push-action@v3
        with:
          file: ./src/WebApps/SocialNetwork.Portal/Dockerfile
          push: true
          tags: |
            mental001/socialnetwork.portal:latest
            mental001/socialnetwork.portal:${{ github.sha }}
      # Build Profile image
      - name: Build and push Profile
        uses: docker/build-push-action@v3
        with:
          file: ./src/Services/Profile/SocialNetwork.Profile.API/Dockerfile
          push: true
          tags: |
            mental001/socialnetwork.profile.api:latest
            mental001/socialnetwork.profile.api:${{ github.sha }}
      # Build IdentityServer image
      - name: Build and push IdentityServer
        uses: docker/build-push-action@v3
        with:
          file: ./src/WebApps/SocialNetwork.IdentityServer/Dockerfile
          push: true
          tags: |
            mental001/socialnetwork.identityserver:latest
            mental001/socialnetwork.identityserver:${{ github.sha }}

  aks:
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
      - name: Checkout the git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup KubeCtl
        uses: azure/setup-kubectl@v2.0

      # Set the target AKS cluster.
      - uses: Azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: SocialNetworkCluster
          resource-group: SocialNetwork

      # Deploy Portal
      - uses: Azure/k8s-deploy@v3.1
        with:
          action: deploy
          manifests: deployment/aks/portal.yaml
          images: mental001/socialnetwork.portal:${{ github.sha }}

      # Deploy Profile
      - uses: Azure/k8s-deploy@v3.1
        with:
          action: deploy
          manifests: deployment/aks/profile.yaml
          images: mental001/socialnetwork.profile.api:${{ github.sha }}

      # Deploy IdentityServer
      - uses: Azure/k8s-deploy@v3.1
        with:
          action: deploy
          manifests: deployment/aks/identityserver.yaml
          images: mental001/socialnetwork.identityserver:${{ github.sha }}

      # Deploy Ingress
      - uses: Azure/k8s-deploy@v3.1
        with:
          action: deploy
          manifests: deployment/aks/ingress.yaml
